services:
  # 1. Cơ sở dữ liệu PostgreSQL
  db:
    image: postgres:15
    container_name: secure-auth-postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - auth-network

  # 2. Công cụ quản lý Database qua Web
  db-manager:
    image: adminer
    container_name: secure-auth-db-manager
    restart: always
    ports:
      - "8082:8080"
    networks:
      - auth-network

  # 3. Ứng dụng Spring Boot
  app:
    image: htquochung/secure-auth-service:v2.1
    container_name: secure-auth-app
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8081:8080"
    environment:
      # Kết nối nội bộ dùng tên service 'db'
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      # Đường dẫn Keys bên trong container (Mapping từ volume)
      JWT_PRIVATE_KEY_FILE: /app/secrets/jwt_private.pem
      JWT_PUBLIC_KEY_FILE: /app/secrets/jwt_public.pem
    volumes:
      # Ánh xạ thư mục secrets từ máy thật vào container
      - ./secrets:/app/secrets
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge

volumes:
  postgres_data: